-- =========================================================
-- 4Wheels CAR RENTAL DATABASE SCHEMA
-- Updated to match 4WheelsDB_v3.txt structure
-- =========================================================
-- Run these commands in your Oracle SQL environment

-- NOTE: You can run the complete 4WheelsDB_v3.txt file instead
-- This is a simplified version for quick setup

-- ============================================
-- 1. Create Car Types Table
-- ============================================
CREATE TABLE Car_Types (
    type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(255)
);

-- Insert sample car types
INSERT INTO CAR_TYPES (TYPE_ID, TYPE_NAME, DESCRIPTION) VALUES (1, 'Sedan', 'Standard sedan cars for everyday use');
INSERT INTO CAR_TYPES (TYPE_ID, TYPE_NAME, DESCRIPTION) VALUES (2, 'SUV', 'Sport Utility Vehicles with more space');
INSERT INTO CAR_TYPES (TYPE_ID, TYPE_NAME, DESCRIPTION) VALUES (3, 'Luxury', 'Premium luxury vehicles');
INSERT INTO CAR_TYPES (TYPE_ID, TYPE_NAME, DESCRIPTION) VALUES (4, 'Sports', 'High-performance sports cars');
INSERT INTO CAR_TYPES (TYPE_ID, TYPE_NAME, DESCRIPTION) VALUES (5, 'Economy', 'Budget-friendly compact cars');

COMMIT;

-- ============================================
-- 2. Create Cars Table
-- ============================================
CREATE TABLE CARS (
    CAR_ID NUMBER PRIMARY KEY,
    TYPE_ID NUMBER NOT NULL,
    BRAND VARCHAR2(50) NOT NULL,
    MODEL VARCHAR2(50) NOT NULL,
    YEAR NUMBER(4) NOT NULL,
    LICENSE_PLATE VARCHAR2(20) UNIQUE NOT NULL,
    DAILY_RATE NUMBER(10, 2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'available' CHECK (STATUS IN ('available', 'rented', 'maintenance')),
    MILEAGE NUMBER(10) DEFAULT 0,
    IMAGE_URL VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_car_type FOREIGN KEY (TYPE_ID) REFERENCES CAR_TYPES(TYPE_ID)
);

-- Create sequence for cars
CREATE SEQUENCE cars_seq START WITH 1 INCREMENT BY 1;

-- Insert sample cars
INSERT INTO CARS (CAR_ID, TYPE_ID, BRAND, MODEL, YEAR, LICENSE_PLATE, DAILY_RATE, STATUS, MILEAGE, IMAGE_URL) 
VALUES (1, 1, 'Toyota', 'Camry', 2023, 'ABC-1234', 49.99, 'available', 15000, 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=500&fit=crop');

INSERT INTO CARS (CAR_ID, TYPE_ID, BRAND, MODEL, YEAR, LICENSE_PLATE, DAILY_RATE, STATUS, MILEAGE, IMAGE_URL) 
VALUES (2, 2, 'Honda', 'CR-V', 2024, 'XYZ-5678', 69.99, 'available', 8000, 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=500&fit=crop');

INSERT INTO CARS (CAR_ID, TYPE_ID, BRAND, MODEL, YEAR, LICENSE_PLATE, DAILY_RATE, STATUS, MILEAGE, IMAGE_URL) 
VALUES (3, 3, 'BMW', '5 Series', 2024, 'LUX-9012', 129.99, 'available', 5000, 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=500&fit=crop');

INSERT INTO CARS (CAR_ID, TYPE_ID, BRAND, MODEL, YEAR, LICENSE_PLATE, DAILY_RATE, STATUS, MILEAGE, IMAGE_URL) 
VALUES (4, 4, 'Mercedes', 'AMG GT', 2024, 'SPT-3456', 199.99, 'available', 3000, 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=500&fit=crop');

INSERT INTO CARS (CAR_ID, TYPE_ID, BRAND, MODEL, YEAR, LICENSE_PLATE, DAILY_RATE, STATUS, MILEAGE, IMAGE_URL) 
VALUES (5, 5, 'Toyota', 'Corolla', 2023, 'ECO-7890', 39.99, 'available', 22000, 'https://images.unsplash.com/photo-1623869675394-c96a2e6d1485?w=800&h=500&fit=crop');

INSERT INTO CARS (CAR_ID, TYPE_ID, BRAND, MODEL, YEAR, LICENSE_PLATE, DAILY_RATE, STATUS, MILEAGE, IMAGE_URL) 
VALUES (6, 2, 'Ford', 'Explorer', 2024, 'SUV-4567', 79.99, 'available', 12000, 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&h=500&fit=crop');

COMMIT;

-- ============================================
-- 3. Create Users Table (Optional)
-- ============================================
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PHONE VARCHAR2(20),
    PASSWORD_HASH VARCHAR2(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create sequence for users
CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;

-- ============================================
-- 4. Create Bookings Table
-- ============================================
CREATE TABLE BOOKINGS (
    BOOKING_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    CAR_ID NUMBER NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    TOTAL_COST NUMBER(10, 2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'pending' CHECK (STATUS IN ('pending', 'confirmed', 'completed', 'cancelled')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT fk_booking_car FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID),
    CONSTRAINT chk_dates CHECK (END_DATE > START_DATE)
);

-- Create sequence for bookings
CREATE SEQUENCE bookings_seq START WITH 1 INCREMENT BY 1;

-- ============================================
-- 5. Create Indexes for Performance
-- ============================================
CREATE INDEX idx_cars_type ON CARS(TYPE_ID);
CREATE INDEX idx_cars_status ON CARS(STATUS);
CREATE INDEX idx_bookings_car ON BOOKINGS(CAR_ID);
CREATE INDEX idx_bookings_user ON BOOKINGS(USER_ID);
CREATE INDEX idx_bookings_dates ON BOOKINGS(START_DATE, END_DATE);

-- ============================================
-- 6. Verification Queries
-- ============================================
-- Check if tables were created
SELECT table_name FROM user_tables WHERE table_name IN ('CAR_TYPES', 'CARS', 'USERS', 'BOOKINGS');

-- View all cars with their types
SELECT 
    c.CAR_ID,
    c.BRAND,
    c.MODEL,
    ct.TYPE_NAME,
    c.DAILY_RATE,
    c.STATUS
FROM CARS c
JOIN CAR_TYPES ct ON c.TYPE_ID = ct.TYPE_ID
ORDER BY c.CAR_ID;

-- Count cars by type
SELECT 
    ct.TYPE_NAME,
    COUNT(*) as CAR_COUNT
FROM CARS c
JOIN CAR_TYPES ct ON c.TYPE_ID = ct.TYPE_ID
GROUP BY ct.TYPE_NAME;
